steps:
  # Сборка Docker образа без кэша
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/telegram-bot:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/telegram-bot:latest'
      - '.'
    
  # Публикация образа в Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/telegram-bot:$COMMIT_SHA'
      
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/telegram-bot:latest'
  
  # Деплой в Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'telegram-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/telegram-bot:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '3'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'PYTHONUNBUFFERED=1'
      - '--set-secrets'
      - 'TELEGRAM_BOT_TOKEN=telegram-bot-token:latest,GOOGLE_SHEETS_SPREADSHEET_ID=google-sheets-id:latest'

# Опции сборки
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Время выполнения
timeout: '1200s'

# Образы для сохранения
images:
  - 'gcr.io/$PROJECT_ID/telegram-bot:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/telegram-bot:latest'
